name: rust-uprobe-libcall-filter
on: [push]
env:
    RUSTUP_TOOLCHAIN: "1.93.1"
    RUSTUP_HOME: "./rust/rustup"
    CARGO_HOME: "./rust/cargo"

jobs:
  build-rust-urpobe-libcall-filter:
    runs-on: codeberg-medium-lazy
    container:
       image: registry.opensuse.org/opensuse/bci/nodejs:latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v6
       with:
        submodules: recursive
        persist-credentials: false
     - name: Cache Rust
       id: cache-rust
       uses: actions/cache@v5
       with:
        path: rust
        key: ${{ runner.os }}-rustup-${{env.RUSTUP_TOOLCHAIN}}
     - name: Install rust
       if: steps.cache-rust.outputs.cache-hit != 'true'
       run: |
              mkdir -p $RUSTUP_HOME
              mkdir -p $CARGO_HOME
              zypper in -y rustup
              rustup install $RUSTUP_TOOLCHAIN
              rustup install nightly
              rustup component add rust-src --toolchain nightly
              rustup component add clippy
     - name: Configure Rust and display version
       run: |
           rustup default nightly
           echo "RUSTUP_TOOLCHAIN=nightly" >> $GITHUB_ENV
           export RUSTUP_TOOLCHAIN=nightly
           echo "PATH=$(dirname $(rustup which cargo)):$(pwd)/rust/cargo/bin:$PATH" >> $GITHUB_ENV
           rustc --version
           cargo --version           
     - name: Build uprobe-libcall-filter-ebpf
       run: | 
          rustup default nightly
          rustup toolchain list
          cargo --version
          cargo install bpf-linker
          cd uprobe-libcall-filter
          cd uprobe-libcall-filter-ebpf
          cargo build --target bpfel-unknown-none -Z build-std=core --release
          cd ..
          cd uprobe-libcall-filter-app
          cargo build --release