name: rust-net-tc-filter
on: [push]
env:
    RUSTUP_TOOLCHAIN: "1.64"
    RUSTUP_HOME: "./rust/rustup"
    CARGO_HOME: "./rust/cargo"

jobs:
  build-rust-net-tc-filter:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       with:
        submodules: recursive
     - name: Cache Rust
       id: cache-rust
       uses: actions/cache@v3
       with:
        path: rust
        key: ${{ runner.os }}-rustup-${{env.RUSTUP_TOOLCHAIN}}
     - name: Install rust
       if: steps.cache-rust.outputs.cache-hit != 'true'
       run: |
              mkdir -p $RUSTUP_HOME
              mkdir -p $CARGO_HOME
              curl https://sh.rustup.rs -sSf | sh -s -- -y
              rustup install $RUSTUP_TOOLCHAIN
              rustup install nightly
              rustup component add rust-src --toolchain nightly
              rustup component add clippy
     - name: Configure Rust and display version
       run: |
           rustup default nightly
           echo "RUSTUP_TOOLCHAIN=nightly" >> $GITHUB_ENV
           export RUSTUP_TOOLCHAIN=nightly
           echo "PATH=$(dirname $(rustup which cargo)):$(pwd)/rust/cargo/bin:$PATH" >> $GITHUB_ENV
           rustc --version
           cargo --version           
     - name: Build net-tc-filter-ebpf
       run: | 
          rustup default nightly
          rustup toolchain list
          cargo --version
          cargo install bpf-linker
          cd net-tc-filter
          cd net-tc-filter-ebpf
          cargo build --target bpfel-unknown-none -Z build-std=core --release